from EinfachVerketteteListe import *
import random

list = EinfachVerketteteListe()
list.addLast(random.randint(0, 100))
list.addLast(4)
list.addLast(2)
list.addLast(random.randint(0, 100))
list.addLast(random.randint(0, 100))
list.addLast(random.randint(0, 100))
list.insertAfter(2, 10)
list.writeList()
print("--------------------------------")
list.delete(2)
list.writeList()
print("Erstes Element: " + str(list.getFirstElem().getObj()))
print("Ist '3' enthalten? " + str(list.find("3")))
print("Ist '5' enthalten? " + str(list.find("5")))
print("letztes Element: " + str(list.getLastElem().getObj()))
print("anz der Elemente: " + str(list.printLength()))
print("Position von 10: " + str(list.index(10)) + " (startet bei 0)")